import type { Character, PublicEvidence, RunBeat, TimelineBeat } from './types.js'

export const timeline: TimelineBeat[] = [
  { beat: 1, title: 'The old secret', truth: 'Le Maître Concierge kept Le Carnet Bleu, despite claiming it vanished years ago.', evidence: ['amelie-rumour', 'madame-ledger'] },
  { beat: 2, title: 'The hiding place', truth: 'He hid the notebook inside Pierre Escargot’s blue dinner jacket.', evidence: ['pierre-pocket', 'madame-glimpse'] },
  { beat: 3, title: 'The switch', truth: 'François switched Pierre and Jacques’s jackets as a secret dinner task.', evidence: ['francois-switch', 'amelie-jackets'] },
  { beat: 4, title: 'The discovery', truth: 'Jacques found the notebook in what he believed was his own jacket and concluded the Concierge had framed him.', evidence: ['jacques-find', 'pierre-label'] },
  { beat: 5, title: 'The route opens', truth: 'Pierre opened the terrace door as an innocent secret action.', evidence: ['pierre-door', 'amelie-draught'] },
  { beat: 6, title: 'Sixty seconds', truth: 'Amélie gave the blackout signal and the host cut the lights for sixty seconds.', evidence: ['amelie-blackout', 'francois-clock'] },
  { beat: 7, title: 'The confrontation', truth: 'Jacques entered the study through the terrace and demanded an explanation. The Concierge realised the jackets had been switched and laughed.', evidence: ['jacques-confronts', 'amelie-laugh'] },
  { beat: 8, title: 'The fatal shove', truth: 'Humiliated and furious, Jacques mimed a shove. The Concierge staged a fall against the desk; in the fiction, the head injury was fatal.', evidence: ['jacques-shove', 'scene-wound'] },
  { beat: 9, title: 'The panic', truth: 'Jacques fled with Le Carnet Bleu before the lights returned.', evidence: ['jacques-flight', 'pierre-shadow'] },
  { beat: 10, title: 'The false culprit', truth: 'Madame Très-Bien searched the desk instead of helping. Pierre found her standing over the body.', evidence: ['madame-search', 'pierre-sees'] },
]

export const publicEvidence: PublicEvidence[] = [
  { id: 'scene-wound', beat: 8, text: 'The Concierge’s staged head wound is beside the sharp corner of the study desk; no weapon is present.' },
]

export const cast: Character[] = [
  {
    id: 'jacques',
    name: 'Jacques Fromage',
    title: 'Disgraced attaché for dairy intelligence',
    costume: 'Cream dinner jacket, medals of uncertain origin',
    publicFace: 'Smooth, vain, and offended by any cheese served below room temperature.',
    privateSecret: 'Years ago you sold one name from Le Carnet Bleu to clear a gambling debt. The Concierge knew.',
    memories: [
      { id: 'jacques-find', kind: 'evidence', beat: 4, availableAfter: 'jacket-switch', text: 'When you put your jacket back on, you found Le Carnet Bleu inside and believed the Concierge had planted it to expose you.' },
      { id: 'jacques-confronts', kind: 'evidence', beat: 7, availableAfter: 'stage-murder', text: 'During the blackout, the Concierge laughed when you accused him of framing you and said the jackets had been switched.' },
      { id: 'jacques-shove', kind: 'secret', beat: 8, availableAfter: 'stage-murder', text: 'Your shove in the study caused the fatal fall. It was an accident, but you panicked.' },
      { id: 'jacques-flight', kind: 'secret', beat: 9, availableAfter: 'stage-murder', text: 'You left the study with Le Carnet Bleu before the lights returned.' },
      { id: 'jacques-duel', kind: 'colour', text: 'Pierre once challenged you to a duel with cocktail umbrellas. You lost.' },
    ],
    actions: [
      {
        id: 'jacques-toast',
        text: 'Insist on a toast to “the glorious ambiguity of loyalty”.',
        cue: 'After the first drink, when the host catches your eye',
        consequence: 'Gives Amélie the coded signal that the blackout sequence is approaching.',
        essential: true,
        beat: 6,
        phase: 'dinner',
        physical: false,
      },
      {
        id: 'jacques-murder',
        text: 'In the darkness, enter the study through the terrace, confront the Concierge, mime one shove without touching them, take the notebook, and leave.',
        cue: 'When the host cuts the lights and quietly calls you to the study',
        consequence: 'Creates the confrontation, accidental death, and flight with the notebook.',
        essential: true,
        beat: 8,
        phase: 'blackout',
        physical: true,
      },
    ],
  },
  {
    id: 'madame',
    name: 'Madame Très-Bien',
    title: 'Widowed patroness of elegant treason',
    costume: 'Black silk, enormous sunglasses, one red glove',
    publicFace: 'Perfectly composed. Treats scandal as a seating-plan problem.',
    privateSecret: 'You have spent years trying to recover Le Carnet Bleu because your late husband appears inside it.',
    memories: [
      { id: 'madame-ledger', kind: 'evidence', beat: 1, text: 'Years ago, you saw a private ledger proving the Concierge still controlled Le Carnet Bleu.' },
      { id: 'madame-glimpse', kind: 'evidence', beat: 2, text: 'Before dinner, you glimpse the Concierge slip a blue notebook into Pierre’s jacket.' },
      { id: 'madame-search', kind: 'secret', beat: 10, availableAfter: 'stage-false-culprit', text: 'During the blackout, you searched the desk for the notebook instead of helping the fallen Concierge.' },
      { id: 'madame-argument', kind: 'secret', text: 'You argued with the Concierge this afternoon and threatened to ruin him.' },
      { id: 'madame-perfume', kind: 'colour', text: 'You deliberately wear the perfume the Concierge hated.' },
    ],
    actions: [
      {
        id: 'madame-message',
        text: 'Pass Pierre a note reading “The peacock remembers Nice.” Refuse to explain.',
        cue: 'Before the main course',
        consequence: 'Creates an apparently sinister link between you and Pierre.',
        essential: false,
        phase: 'dinner',
        physical: true,
      },
      {
        id: 'madame-search-action',
        text: 'After Jacques leaves the study, enter, search the desk, and remain beside the Concierge until Pierre discovers you.',
        cue: 'During the blackout, when the host quietly calls your name',
        consequence: 'Creates the convincing false-suspect scene.',
        essential: true,
        beat: 10,
        phase: 'blackout',
        physical: true,
      },
    ],
  },
  {
    id: 'francois',
    name: 'François Croissant',
    title: 'Pastry magnate and occasional courier',
    costume: 'White tuxedo, flour-dusted carnation',
    publicFace: 'Cheerful, indiscreet, and constantly checking his watch.',
    privateSecret: 'Your bakery is a dead-drop network. Tonight’s tasks arrived through it.',
    memories: [
      { id: 'francois-switch', kind: 'evidence', beat: 3, availableAfter: 'jacket-switch', text: 'You switched Jacques and Pierre’s jackets, assuming the instruction was a joke.' },
      { id: 'francois-clock', kind: 'evidence', beat: 6, availableAfter: 'stage-false-culprit', text: 'The blackout lasted almost exactly sixty seconds; you timed it by habit.' },
      { id: 'francois-letter', kind: 'secret', text: 'The instruction envelope bore Madame’s family crest, probably forged.' },
      { id: 'francois-kiss', kind: 'colour', text: 'Pierre kissed you at Cannes and has denied it ever since.' },
      { id: 'francois-recipe', kind: 'colour', text: 'The Concierge stole your recipe for diplomatic brioche.' },
    ],
    actions: [
      {
        id: 'francois-switch-action',
        text: 'Switch Jacques and Pierre’s jackets without being seen.',
        cue: 'Once the host has persuaded both of them to remove their jackets',
        consequence: 'Moves the notebook from Pierre to Jacques.',
        essential: true,
        beat: 3,
        phase: 'dinner',
        physical: true,
      },
    ],
  },
  {
    id: 'pierre',
    name: 'Pierre Escargot',
    title: 'Retired field agent with suspiciously quick reflexes',
    costume: 'Blue dinner jacket with a “P. Escargot” label, silver snail pin',
    publicFace: 'Slow-speaking observer who notices every exit.',
    privateSecret: 'You once worked for the Concierge and stole the study key for Amélie tonight.',
    memories: [
      { id: 'pierre-pocket', kind: 'evidence', beat: 2, text: 'Before dinner, your blue jacket feels oddly heavy at the inner pocket.' },
      { id: 'pierre-label', kind: 'evidence', beat: 4, text: 'Your jacket has a hand-sewn “P. Escargot” label. Jacques’s jacket does not.' },
      { id: 'pierre-door', kind: 'evidence', beat: 5, availableAfter: 'terrace-route', text: 'You opened the terrace door because your secret instruction demanded it.' },
      { id: 'pierre-shadow', kind: 'evidence', beat: 9, availableAfter: 'stage-murder', text: 'Near the end of the blackout, a man shaped like Jacques passed from the study toward the hall.' },
      { id: 'pierre-sees', kind: 'evidence', beat: 10, availableAfter: 'stage-false-culprit', text: 'When the lights returned, you found Madame over the Concierge with the desk open.' },
      { id: 'pierre-key', kind: 'secret', text: 'You stole the study key and gave it to Amélie before dinner.' },
    ],
    actions: [
      {
        id: 'pierre-door-action',
        text: 'Open the terrace door and leave it open.',
        cue: 'When the host deliberately mentions Marseille',
        consequence: 'Creates Jacques’s unseen route to the study.',
        essential: true,
        beat: 5,
        phase: 'dinner',
        physical: true,
      },
      {
        id: 'pierre-discovery',
        text: 'When the lights return, go to the study and announce that Madame is standing over the Concierge.',
        cue: 'When the host restores the lights',
        consequence: 'Introduces the body and the false suspect to the table.',
        essential: true,
        beat: 10,
        phase: 'blackout',
        physical: true,
      },
    ],
  },
  {
    id: 'amelie',
    name: 'Amélie Voulez-Vous',
    title: 'Cabaret cryptographer',
    costume: 'Sequins, opera gloves, emerald ring',
    publicFace: 'Speaks in questions and treats every sentence as a code.',
    privateSecret: 'You stole the study key, but only to copy the Concierge’s private radio frequencies.',
    memories: [
      { id: 'amelie-rumour', kind: 'evidence', beat: 1, text: 'The Concierge once drunkenly admitted Le Carnet Bleu never left this house.' },
      { id: 'amelie-jackets', kind: 'evidence', beat: 3, availableAfter: 'jacket-switch', text: 'You saw François carrying Pierre and Jacques’s jackets near the hall.' },
      { id: 'amelie-draught', kind: 'evidence', beat: 5, availableAfter: 'terrace-route', text: 'Just before the blackout, you felt a strong draught from the terrace.' },
      { id: 'amelie-blackout', kind: 'evidence', beat: 6, availableAfter: 'blackout-signal', text: 'You gave the coded blackout signal immediately after Jacques’s toast.' },
      { id: 'amelie-laugh', kind: 'evidence', beat: 7, availableAfter: 'stage-murder', text: 'In the darkness, you heard the Concierge laugh in the study, then a crash.' },
      { id: 'amelie-key', kind: 'secret', text: 'You stole the study key with Pierre’s help, but returned it before dinner.' },
    ],
    actions: [
      {
        id: 'amelie-blackout-action',
        text: 'Immediately after Jacques’s toast, give the host the agreed signal. The host—not you—controls the real lights.',
        cue: 'After Jacques toasts the glorious ambiguity of loyalty',
        consequence: 'Starts the sixty-second blackout safely and unambiguously.',
        essential: true,
        beat: 6,
        phase: 'dinner',
        physical: false,
      },
    ],
  },
]

export const runPlan: RunBeat[] = [
  {
    id: 'coded-toast',
    phase: 'dinner',
    title: 'Begin the coded chain',
    trigger: 'After the first drink',
    operator: 'Catch Jacques’s eye and let him give the coded toast.',
    actionIds: ['jacques-toast'],
    dependsOn: [],
    essential: true,
  },
  {
    id: 'false-message',
    phase: 'dinner',
    title: 'Plant the false conspiracy',
    trigger: 'Before the main course',
    operator: 'Make sure Madame can pass Pierre her note without an announcement.',
    actionIds: ['madame-message'],
    dependsOn: [],
    essential: false,
  },
  {
    id: 'jacket-switch',
    phase: 'dinner',
    title: 'Move the notebook',
    trigger: 'After Jacques and Pierre remove their jackets',
    operator: 'Complain that the room is warm until both jackets come off, then give François a clear opening.',
    actionIds: ['francois-switch-action'],
    dependsOn: [],
    essential: true,
  },
  {
    id: 'terrace-route',
    phase: 'dinner',
    title: 'Open the route to the study',
    trigger: 'After the jackets have been switched',
    operator: 'Tell a short story that deliberately mentions Marseille so Pierre receives his cue.',
    actionIds: ['pierre-door-action'],
    dependsOn: ['jacket-switch'],
    essential: true,
  },
  {
    id: 'blackout-signal',
    phase: 'dinner',
    title: 'Receive the blackout signal',
    trigger: 'After the terrace door is open and Jacques has toasted',
    operator: 'Wait for Amélie’s signal. Do not cut the lights before both prerequisite beats are complete.',
    actionIds: ['amelie-blackout-action'],
    dependsOn: ['coded-toast', 'terrace-route'],
    essential: true,
  },
  {
    id: 'stage-murder',
    phase: 'blackout',
    title: 'Stage the confrontation and fatal fall',
    trigger: 'Immediately after the blackout signal',
    operator: 'Cut the lights. Quietly call Jacques to the study. Play the confrontation, mime the shove with no contact, stage the fall, and let Jacques leave with the notebook.',
    actionIds: ['jacques-murder'],
    dependsOn: ['blackout-signal'],
    essential: true,
  },
  {
    id: 'stage-false-culprit',
    phase: 'blackout',
    title: 'Create the false-suspect tableau',
    trigger: 'After Jacques has left the study',
    operator: 'Call Madame into the study to search the desk. Restore the lights only when she is in place, then cue Pierre to discover her.',
    actionIds: ['madame-search-action', 'pierre-discovery'],
    dependsOn: ['stage-murder'],
    essential: true,
  },
]
