import type { Character, PublicEvidence, RunBeat, TimelineBeat } from './types.js'
import type { ClueDeck } from './definition/contract.js'

export const timeline: TimelineBeat[] = [
  {
    beat: 1,
    title: 'The stolen song',
    truth: 'The celebrated waltz La Dernière Marée was composed by Anaïs Loret, although Henri Valois registered and published it in his own name.',
    evidence: ['mathilde-manuscript', 'colette-melody'],
  },
  {
    beat: 2,
    title: 'The impresario’s bargain',
    truth: 'Armand Delatour witnessed the disguised purchase of Anaïs’s manuscript and then used his influence to keep questions about the registration out of print.',
    evidence: ['gabriel-contract', 'remy-review'],
  },
  {
    beat: 3,
    title: 'The hidden publisher',
    truth: 'Solange Béraud secretly owns Éditions du Méridien, the company still collecting the song’s royalties. Restoring Anaïs’s authorship would expose Solange’s fraud and end her income.',
    evidence: ['gabriel-dividends', 'remy-company'],
  },
  {
    beat: 4,
    title: 'The borrowed hand',
    truth: 'Before dinner, Solange asked Mathilde to address an archive label to Armand over blue carbon, then kept and trimmed the duplicate.',
    evidence: ['mathilde-label', 'colette-carbon'],
  },
  {
    beat: 5,
    title: 'The sixth envelope',
    truth: 'Rémy counted five sealed restitution packets before any were opened. While the room listened, Solange placed a sixth envelope addressed privately to Armand on top of his notebook.',
    evidence: ['remy-count', 'gabriel-stack'],
  },
  {
    beat: 6,
    title: 'The final recording',
    truth: 'Armand opened the extra envelope during Anaïs’s original recording. He collapsed before the final refrain, while Solange remained close enough to watch that he handled it.',
    evidence: ['colette-fall', 'gabriel-clock'],
  },
  {
    beat: 7,
    title: 'A deliberate murder',
    truth: 'The extra envelope fictionally concealed a poisoned glass sliver beneath its inner fold. The carbon copy of Mathilde’s handwriting was attached to frame her.',
    evidence: ['scene-envelope', 'mathilde-label', 'gabriel-trap'],
  },
  {
    beat: 8,
    title: 'The carbon fragment',
    truth: 'Solange trimmed Mathilde’s carbon-copy address into a label for the murder envelope, but its missing corner remained caught inside her document folio.',
    evidence: ['mathilde-carbon', 'remy-folio'],
  },
  {
    beat: 9,
    title: 'The missing composer',
    truth: 'Only after Armand collapsed, Mathilde retrieved—or openly directed Rémy to retrieve—Anaïs’s original score from the study drawer because she believed the promised restitution would otherwise disappear again.',
    evidence: ['mathilde-retrieval', 'colette-sees'],
  },
]

export const publicEvidence: PublicEvidence[] = [
  {
    id: 'scene-envelope',
    beat: 7,
    text: 'A blue carbon-copy label on the sixth envelope is in Mathilde’s hand and reads “Armand Delatour — private”. The host card identifies a fictional poisoned glass sliver beneath the inner fold and a pinprick on Armand’s thumb. The safe prop contains no glass, point, or substance.',
  },
]

export const clueDecks: ClueDeck[] = [
  {
    id: 'study-archive',
    label: 'Study archive',
    settingField: 'playableSpaces',
    settingValue: 'Staged study',
    clues: [
      { id: 'clue-score-date', beat: 1, text: 'Anaïs Loret’s working score is dated four months before Henri Valois registered La Dernière Marée; its corrections match the melody on Colette’s test pressing.' },
      { id: 'clue-registration-note', beat: 2, text: 'Armand’s file copy of Henri’s contract bears his witness signature and a margin note: “Fauré review withdrawn; registration may proceed without challenge.”' },
      { id: 'clue-publisher-deed', beat: 3, text: 'A bearer-share deed names Solange Béraud as the sole beneficial owner of Éditions du Méridien.' },
    ],
  },
  {
    id: 'dining-room-papers',
    label: 'Dining-room papers',
    settingField: 'playableSpaces',
    settingValue: 'Dining room',
    clues: [
      { id: 'clue-label-indent', beat: 4, text: 'The archive label Mathilde addressed before dinner left a deep impression on its retained top sheet; the blue carbon duplicate is missing.' },
      { id: 'clue-envelope-fibre', beat: 8, text: 'A torn blue corner in Solange’s folio fits the missing corner of the carbon-copy address label attached to Armand’s extra envelope.' },
    ],
  },
]

export const cast: Character[] = [
  {
    id: 'mathilde',
    name: 'Mathilde Loret',
    title: 'Music archivist and heir to Anaïs Loret',
    costume: 'Ink-blue evening dress, reading glasses, a ribbon-bound score',
    publicFace: 'Exacting, contained, and unimpressed by inherited prestige. You correct dates the way other people correct insults.',
    invitationPretext: 'Armand asked you to authenticate a newly discovered score before the house archive is dispersed.',
    invitationPromise: '“Come to Maison Bleue. Before midnight, Anaïs Loret will have her name back.”',
    privateIdentity: 'You are Anaïs Loret’s granddaughter and the only person who has spent years proving that La Dernière Marée was hers.',
    privateObjective: 'Recover Anaïs’s original score, force a public acknowledgment of her authorship, and stop the evidence being divided into private settlements again.',
    privateSecret: 'Armand told you Anaïs’s original score would be waiting in the study’s west drawer. You sent him a furious note promising disgrace if he tried to sell it one final time. After he collapses, you take the score—or openly direct Rémy to retrieve it—rather than leave it in anyone else’s custody.',
    traits: ['Forensically precise', 'Slow to trust inherited authority', 'Fiercely protective of Anaïs’s work'],
    objectives: [
      { id: 'mathilde-credit', title: 'Restore the credit', text: 'Make two guests state openly that Anaïs composed La Dernière Marée.', phase: 'any', points: 2 },
      { id: 'mathilde-score', title: 'Keep the score whole', text: 'Recover the original score and prevent anyone from separating its pages.', phase: 'any', points: 1 },
      { id: 'mathilde-threat', title: 'Explain the threat', text: 'Before the vote, convince one guest that your threatening note was not a murder plan.', phase: 'investigation', points: 1 },
    ],
    relationships: [
      { roleId: 'gabriel', text: 'Gabriel inherited the public credit that should have belonged to your family.' },
      { roleId: 'colette', text: 'Colette’s voice made the stolen song famous, and she knows whose melody she first heard.' },
      { roleId: 'solange', text: 'Solange offered free legal help, but asked oddly specific questions about your handwriting.' },
    ],
    secrets: [
      {
        id: 'mathilde-manuscript',
        kind: 'evidence',
        aboutRoleIds: ['gabriel', 'colette'],
        beat: 1,
        text: 'Anaïs’s ribbon-bound working score predates Henri Valois’s registration by four months. Its revisions match the version Colette recorded before the public premiere.',
      },
      {
        id: 'mathilde-label',
        kind: 'evidence',
        aboutRoleIds: ['solange'],
        beat: 4,
        text: 'Before dinner, Solange asked you to write “Armand Delatour — private” on an archive label over blue carbon. She returned the top sheet but kept the duplicate.',
      },
      {
        id: 'mathilde-carbon',
        kind: 'evidence',
        aboutRoleIds: ['solange'],
        beat: 8,
        availableAfter: 'stage-collapse',
        text: 'The blue address label on Armand’s extra envelope is the carbon duplicate you made. Its missing corner fits a torn fragment protruding from the inner pocket of Solange’s open folio.',
      },
      {
        id: 'mathilde-retrieval',
        kind: 'secret',
        aboutRoleIds: ['colette'],
        beat: 9,
        availableAfter: 'recover-score',
        text: 'Only after Armand collapsed, you took Anaïs’s score from the west drawer or openly directed Rémy to retrieve it as your proxy. Neither of you touched Armand or the extra envelope.',
      },
      {
        id: 'mathilde-threat-note',
        kind: 'secret',
        text: 'Your note to Armand reads: “Return her name tonight, or I will make certain yours survives only in disgrace.”',
      },
      {
        id: 'mathilde-packet',
        kind: 'evidence',
        aboutRoleIds: ['gabriel', 'solange'],
        availableAfter: 'declare-scene',
        text: 'Your restitution packet contains Armand’s signed correction naming Anaïs as sole composer and assigning her estate the authorship share. It needs the current publisher’s countersignature to take effect.',
      },
    ],
    actions: [
      {
        id: 'mathilde-demand',
        text: 'Place Anaïs’s replica working score beside the blue notebook. Read the date aloud and demand that Armand name the true composer before anyone opens a private packet.',
        cue: 'When Armand displays the five sealed packets',
        consequence: 'Makes stolen authorship the public conflict and establishes the oldest dated evidence.',
        essential: true,
        beat: 1,
        phase: 'opening',
        physical: true,
        requires: ['replica-scores', 'notebook'],
      },
      {
        id: 'mathilde-retrieve-score',
        text: 'After Armand collapses, wait until Colette stops the recording and lays her handkerchief beside the gramophone. Then enter the staged study, remove Anaïs’s replica original score from the west drawer, and return holding it. If you need seated play, openly direct Rémy to retrieve it as your named proxy. Do not conceal what either of you is doing.',
        cue: 'When Colette lays her handkerchief beside the stopped gramophone',
        consequence: 'Secures the authorship evidence while giving you a suspicious reason to leave the room.',
        essential: true,
        beat: 9,
        phase: 'opening',
        physical: true,
        requires: ['replica-scores', 'staged-area', 'no-contact'],
      },
    ],
  },
  {
    id: 'gabriel',
    name: 'Gabriel Valois',
    title: 'Publisher and son of the credited composer',
    costume: 'Ivory dinner jacket, black bow tie, a gold tuning-fork pin',
    publicFace: 'Warm, cultivated, and practised at turning inheritance into charm. You speak of legacy whenever ownership would sound vulgar.',
    invitationPretext: 'Armand invited you to approve a final anniversary edition of your father’s most famous work.',
    invitationPromise: '“Come to Maison Bleue. Before midnight, I will give you the contract your father feared.”',
    privateIdentity: 'You discovered the stolen authorship two years ago and have anonymously paid Mathilde from your own dividends without admitting why.',
    privateObjective: 'End the false credit without destroying every musician and employee whose livelihood depends on the catalogue.',
    privateSecret: 'You knew your father was not the composer and quietly diverted part of your royalties to Mathilde. You also found dividend slips proving Solange receives more from the song than your family does.',
    traits: ['Disarmingly gracious', 'Ashamed of unearned prestige', 'Protective of people tied to the catalogue'],
    objectives: [
      { id: 'gabriel-open-contract', title: 'Publish the contract', text: 'Show the “manuscript and silence” clause to another guest.', phase: 'investigation', points: 1 },
      { id: 'gabriel-workers', title: 'Protect the catalogue', text: 'Win support for restitution that does not destroy the musicians’ livelihoods.', phase: 'investigation', points: 1 },
      { id: 'gabriel-payments', title: 'Own the payments', text: 'Reveal your anonymous payments to Mathilde before someone else exposes them.', phase: 'any', points: 2 },
    ],
    relationships: [
      { roleId: 'mathilde', text: 'You owe Mathilde the truth and fear she will mistake your secret payments for hush money.' },
      { roleId: 'remy', text: 'Rémy’s glowing review made your father untouchable.' },
      { roleId: 'solange', text: 'Solange manages the rights and insists the ownership structure is ordinary.' },
    ],
    secrets: [
      {
        id: 'gabriel-contract',
        kind: 'evidence',
        aboutRoleIds: ['solange', 'mathilde'],
        beat: 2,
        text: 'Your father’s private contract calls Anaïs’s payment “purchase of manuscript and silence”. Armand signed as witness; Solange’s predecessor registered the altered title page.',
      },
      {
        id: 'gabriel-dividends',
        kind: 'evidence',
        aboutRoleIds: ['solange'],
        beat: 3,
        text: 'The latest dividend slip sends sixty percent of La Dernière Marée’s royalties to Éditions du Méridien, then routes them to an account initialled S.B.',
      },
      {
        id: 'gabriel-stack',
        kind: 'evidence',
        aboutRoleIds: ['solange', 'remy'],
        beat: 5,
        availableAfter: 'stage-collapse',
        text: 'Rémy counted five named packets. During the recording you saw Solange lean over Armand’s notebook; afterward a sixth envelope addressed to Armand lay on top of it.',
      },
      {
        id: 'gabriel-clock',
        kind: 'evidence',
        aboutRoleIds: ['colette', 'solange'],
        beat: 6,
        availableAfter: 'stage-collapse',
        text: 'Armand opened the extra envelope during the second verse and collapsed before Colette reached the final refrain. Solange was watching him rather than the gramophone.',
      },
      {
        id: 'gabriel-trap',
        kind: 'evidence',
        aboutRoleIds: ['solange', 'mathilde'],
        beat: 7,
        availableAfter: 'declare-scene',
        text: 'When Rémy opened the sixth envelope for inspection, you saw the host card marking a narrow pocket beneath its inner fold. It was built to hide the fictional poisoned sliver; the separate address label was added to frame someone else.',
      },
      {
        id: 'gabriel-payments-secret',
        kind: 'secret',
        aboutRoleIds: ['mathilde'],
        text: 'For two years you have sent Mathilde anonymous payments equal to half your personal royalties. You never explained that they were restitution.',
      },
    ],
    actions: [
      {
        id: 'gabriel-open-statement',
        text: 'Open your named packet. Show Henri’s original “manuscript and silence” contract, then read the attached current dividend statement aloud. Ask Solange why Éditions du Méridien receives the majority of the song’s income.',
        cue: 'After Mathilde dates Anaïs’s working score',
        consequence: 'Turns an artistic theft into a current financial motive and exposes the hidden publisher.',
        essential: true,
        beat: 3,
        phase: 'opening',
        physical: true,
        requires: ['paper-notes'],
      },
    ],
  },
  {
    id: 'colette',
    name: 'Colette Dumas',
    title: 'Chanteuse who made La Dernière Marée famous',
    costume: 'Midnight velvet, opera gloves, a silver-blue handkerchief',
    publicFace: 'Magnetic, amused, and allergic to solemnity. You remember every room by how it sounded when the truth entered.',
    invitationPretext: 'Armand hired you to play the surviving test recording at a private catalogue dinner.',
    invitationPromise: '“Come to Maison Bleue. Before midnight, the world will hear whose song you sang.”',
    privateIdentity: 'You heard Anaïs compose the waltz and sang on the test pressing before Henri’s name appeared on it.',
    privateObjective: 'Make the recording and your testimony impossible to suppress, while admitting that you accepted fame after Anaïs was erased.',
    privateSecret: 'You recognised the theft before the premiere and performed anyway. You later lied to Mathilde that the test pressing had been destroyed.',
    traits: ['Commanding without effort', 'Remembers sound precisely', 'Uses wit to delay confession'],
    objectives: [
      { id: 'colette-recording', title: 'Play the source', text: 'Make every guest hear the test pressing name Anaïs before Armand’s collapse.', phase: 'any', points: 1 },
      { id: 'colette-witness', title: 'Name the composer', text: 'State publicly when and where you first heard Anaïs play the melody.', phase: 'any', points: 2 },
      { id: 'colette-fame', title: 'Admit the bargain', text: 'Tell Mathilde why you performed after learning the credit was false.', phase: 'investigation', points: 1 },
    ],
    relationships: [
      { roleId: 'mathilde', text: 'Mathilde deserves your testimony and may never forgive how long you withheld it.' },
      { roleId: 'remy', text: 'Rémy praised your performance while privately warning that the melody was stolen.' },
      { roleId: 'solange', text: 'You saw Solange practise Mathilde’s handwriting and pretended not to notice.' },
    ],
    secrets: [
      {
        id: 'colette-melody',
        kind: 'evidence',
        aboutRoleIds: ['mathilde', 'gabriel'],
        beat: 1,
        text: 'On the test pressing, you announce “Anaïs Loret at the piano” before the first notes. Henri Valois was not present at the session.',
      },
      {
        id: 'colette-carbon',
        kind: 'evidence',
        aboutRoleIds: ['solange', 'mathilde'],
        beat: 4,
        text: 'Before dinner you saw Solange trim the blue carbon duplicate of Mathilde’s archive label and slide it into her folio. Solange said the duplicate was for the seating plan.',
      },
      {
        id: 'colette-fall',
        kind: 'evidence',
        aboutRoleIds: ['solange'],
        beat: 6,
        availableAfter: 'stage-collapse',
        text: 'While the recording played, you saw Armand open an extra envelope from the top of his notebook. Solange watched his hands; he collapsed before your final cue.',
      },
      {
        id: 'colette-sees',
        kind: 'evidence',
        aboutRoleIds: ['mathilde'],
        beat: 9,
        availableAfter: 'recover-score',
        text: 'Mathilde remained in the dining room until after Armand collapsed. Only then did she retrieve Anaïs’s score or openly direct Rémy to retrieve it as her proxy.',
      },
      {
        id: 'colette-silence',
        kind: 'secret',
        aboutRoleIds: ['remy'],
        text: 'Rémy warned you before the premiere that Anaïs had written the melody. You sang anyway because it was the first role that could make you famous.',
      },
      {
        id: 'colette-packet',
        kind: 'evidence',
        aboutRoleIds: ['mathilde', 'remy'],
        availableAfter: 'declare-scene',
        text: 'Your restitution packet contains the original studio log naming Anaïs at the piano and Armand’s release cancelling the confidentiality promise he used to silence you.',
      },
    ],
    actions: [
      {
        id: 'colette-play-recording',
        text: 'Start the prepared gramophone track and announce that it is Anaïs Loret’s surviving test recording. If the controls are not within reach, direct Rémy to start and stop them for you. When Armand collapses, stop the track and lay your silver-blue handkerchief beside the gramophone. Stay there while Mathilde follows that cue.',
        cue: 'After Gabriel reads the dividend statement',
        consequence: 'Proves the stolen authorship and focuses the room while the sixth envelope is introduced.',
        essential: true,
        beat: 6,
        phase: 'opening',
        physical: true,
        requires: ['recording-track', 'handkerchief'],
      },
    ],
  },
  {
    id: 'remy',
    name: 'Rémy Fauré',
    title: 'Retired critic and reluctant executor',
    costume: 'Sober blue suit, old pocket watch, folded evening programme',
    publicFace: 'Dry, exact, and devastatingly economical. You can make a compliment sound like evidence under oath.',
    invitationPretext: 'Armand named you neutral executor of the five restitution packets.',
    invitationPromise: '“Come to Maison Bleue. Before midnight, you may finally publish the review you buried.”',
    privateIdentity: 'You wrote the only contemporary review identifying Anaïs as the likely composer, then withdrew it in exchange for a prestigious editorship.',
    privateObjective: 'Preserve the packets as evidence, expose the rights fraud, and decide whether to publish your own corruption with the truth.',
    privateSecret: 'Armand bought your silence with the editorship that made your career. You kept the withdrawn review and a company registry extract linking Solange to the royalties.',
    traits: ['Exact with documents', 'Sparing with emotion', 'Unable to resist correcting a false chronology'],
    objectives: [
      { id: 'remy-packets', title: 'Preserve the packets', text: 'Account publicly for all five named restitution packets.', phase: 'any', points: 1 },
      { id: 'remy-review', title: 'Publish the review', text: 'Give your withdrawn review to Mathilde or read its conclusion aloud.', phase: 'investigation', points: 2 },
      { id: 'remy-bribe', title: 'Name your price', text: 'Admit what Armand gave you for withdrawing the review.', phase: 'investigation', points: 1 },
    ],
    relationships: [
      { roleId: 'colette', text: 'Colette knew your warning was true and went onstage anyway.' },
      { roleId: 'gabriel', text: 'Gabriel inherited a lie but may be the only publisher willing to correct it.' },
      { roleId: 'solange', text: 'Solange’s company extract is the most current crime in the room.' },
    ],
    secrets: [
      {
        id: 'remy-review',
        kind: 'evidence',
        aboutRoleIds: ['colette', 'gabriel'],
        beat: 2,
        text: 'Your withdrawn review says the waltz’s melodic hand is Anaïs Loret’s and notes that Armand refused to show the registration papers. The next morning he offered you the editorship; you withdrew the review.',
      },
      {
        id: 'remy-company',
        kind: 'evidence',
        aboutRoleIds: ['solange'],
        beat: 3,
        text: 'A registry extract identifies Solange as beneficial owner of Éditions du Méridien through two nominee companies.',
      },
      {
        id: 'remy-count',
        kind: 'evidence',
        aboutRoleIds: ['solange'],
        beat: 5,
        availableAfter: 'display-packets',
        text: 'You counted exactly five sealed packets—one bearing each guest’s name—and placed them clear of Armand’s notebook before the recording began.',
      },
      {
        id: 'remy-folio',
        kind: 'evidence',
        aboutRoleIds: ['solange', 'mathilde'],
        beat: 8,
        availableAfter: 'stage-collapse',
        text: 'A torn blue corner protruding from the inner pocket of Solange’s open folio fits the missing corner of the carbon-copy address label attached to the extra envelope.',
      },
      {
        id: 'remy-bribe',
        kind: 'secret',
        text: 'Armand arranged your editorship on the condition that your review never reached print. Every later honour grew from that bargain.',
      },
      {
        id: 'remy-packet',
        kind: 'evidence',
        aboutRoleIds: ['colette', 'gabriel'],
        availableAfter: 'declare-scene',
        text: 'Your restitution packet contains Armand’s signed letter admitting that he bought your withdrawn review with the editorship and asking that both documents be published together.',
      },
    ],
    actions: [
      {
        id: 'remy-count-packets',
        text: 'Count the five named restitution packets aloud, show each name to the table, and place the packets in a row away from Armand’s blue notebook.',
        cue: 'When Armand announces that the five packets are restitution',
        consequence: 'Creates a witnessed baseline that makes the later sixth envelope impossible to dismiss as part of Armand’s plan.',
        essential: true,
        beat: 5,
        phase: 'opening',
        physical: true,
        requires: ['paper-notes'],
      },
      {
        id: 'remy-declare-scene',
        text: 'After Mathilde returns, spread the already-open safe envelope flat and read its evidence card aloud. Then announce only the visible facts: all five named packets are accounted for—four sealed and Gabriel’s open—the sixth envelope addressed to Armand lies on the notebook, and Mathilde returned from the study with Anaïs’s score.',
        cue: 'When Mathilde returns from the staged study',
        consequence: 'Opens the investigation with a precise scene account and an immediate false suspect.',
        essential: true,
        beat: 7,
        phase: 'opening',
        physical: true,
        requires: ['paper-notes', 'no-contact'],
      },
    ],
  },
  {
    id: 'solange',
    name: 'Solange Béraud',
    title: 'Copyright solicitor to the Valois catalogue',
    costume: 'Black satin, pearl cuffs, a slim blue document folio',
    publicFace: 'Calm, attentive, and always ready with the clause everyone else overlooked. You make ownership sound like a natural law.',
    invitationPretext: 'Armand asked you to execute the rights transfer and certify that every claim is final.',
    invitationPromise: '“Come to Maison Bleue. Before midnight, I will return the company that should never have been yours.”',
    privateIdentity: 'You secretly own the shell publisher that has taken most of the stolen song’s royalties for fifteen years.',
    privateObjective: 'Destroy the transfer, keep your ownership hidden, and direct suspicion toward Mathilde’s public anger.',
    privateSecret: 'You prepared the fictional poisoned-splinter envelope that kills Armand. The transfer inventory told you Mathilde expected Anaïs’s original score in the west drawer. You used the carbon duplicate of her handwriting, slipped the envelope onto the blue notebook during Colette’s recording, and counted on her threat and dash to complete the frame.',
    traits: ['Legally meticulous', 'Soft-spoken under pressure', 'Treats morality as defective drafting'],
    objectives: [
      { id: 'solange-folio', title: 'Protect the folio', text: 'Keep the blue carbon fragment out of another guest’s hands.', phase: 'investigation', points: 1 },
      { id: 'solange-frame', title: 'Frame the heir', text: 'Make two guests openly argue that Mathilde prepared the extra envelope.', phase: 'any', points: 1 },
      { id: 'solange-escape', title: 'Keep the company', text: 'Avoid conviction and retain the rights-transfer packet.', phase: 'investigation', points: 2 },
    ],
    relationships: [
      { roleId: 'mathilde', text: 'Mathilde’s anger and handwriting are the two instruments of your frame.' },
      { roleId: 'gabriel', text: 'Gabriel has seen dividend slips that point toward your private account.' },
      { roleId: 'remy', text: 'Rémy brought a registry extract that could expose your ownership.' },
    ],
    secrets: [
      {
        id: 'solange-envelope',
        kind: 'secret',
        aboutRoleIds: ['mathilde'],
        beat: 7,
        availableAfter: 'stage-collapse',
        text: 'You attached the carbon duplicate of Mathilde’s handwriting to a safe prop envelope representing a poisoned-splinter trap, then placed it on Armand’s notebook so he would open it during the recording.',
      },
      {
        id: 'solange-transfer',
        kind: 'evidence',
        aboutRoleIds: ['gabriel', 'mathilde'],
        text: 'The packet addressed to you transfers Éditions du Méridien and its catalogue income to Anaïs Loret’s estate. Armand intended you to sign it in front of everyone.',
      },
      {
        id: 'solange-warning',
        kind: 'secret',
        aboutRoleIds: ['remy'],
        text: 'You know Rémy obtained a current registry extract. You searched his coat before dinner but found only the empty document sleeve.',
      },
      {
        id: 'solange-gabriel',
        kind: 'colour',
        aboutRoleIds: ['gabriel'],
        text: 'Gabriel’s anonymous payments to Mathilde came from his personal income, not the publisher. You planned to describe them as hush money if challenged.',
      },
      {
        id: 'solange-threat-note',
        kind: 'secret',
        aboutRoleIds: ['mathilde'],
        text: 'You saw Mathilde’s note on Armand’s desk: “Return her name tonight, or I will make certain yours survives only in disgrace.” You intend to quote it after his death.',
      },
    ],
    actions: [
      {
        id: 'solange-place-envelope',
        text: 'When Colette starts the recording, take the host-identifiable safe prop envelope from your blue folio and place it addressed-side up on Armand’s notebook. Leave the folio open at your place. The identifying mark stays on the envelope’s reverse. Do not add any object or substance, touch another person, or handle any real food or drink.',
        cue: 'After Rémy has counted five named packets and the room turns toward the gramophone',
        consequence: 'Introduces the sixth envelope that stages Armand’s murder and attempts to frame Mathilde.',
        essential: true,
        beat: 7,
        phase: 'opening',
        physical: true,
        requires: ['notebook', 'paper-notes', 'solange-folio', 'no-contact'],
      },
    ],
  },
]

export const runPlan: RunBeat[] = [
  {
    id: 'seat-the-claimants',
    phase: 'opening',
    title: 'Seat the five claimants',
    trigger: 'As the last guest takes their place',
    operator: 'Give everyone one quiet minute in character. Place the blue notebook and five sealed named packets at Armand’s place. Give Mathilde the replica working score; place the separate replica original score in the staged-study drawer. Solange keeps the host-identifiable safe murder envelope hidden in her folio.',
    actionIds: [],
    dependsOn: [],
    essential: false,
  },
  {
    id: 'display-packets',
    phase: 'opening',
    title: 'Count the restitution packets',
    trigger: 'Once everyone is seated',
    operator: 'Tell the room: “Each of you was promised something different. These five packets are not bargains; they are restitution.” Ask Rémy, as executor, to count the five sealed named packets and place them in a witnessed row away from the notebook.',
    actionIds: ['remy-count-packets'],
    dependsOn: [],
    essential: true,
  },
  {
    id: 'open-the-account',
    phase: 'opening',
    title: 'Name the true composer',
    trigger: 'After Rémy confirms exactly five sealed packets',
    operator: 'Display the blue notebook, then cue Mathilde to place Anaïs’s replica working score beside it and date the manuscript.',
    actionIds: ['mathilde-demand'],
    dependsOn: ['display-packets'],
    essential: true,
  },
  {
    id: 'reveal-the-royalties',
    phase: 'opening',
    title: 'Follow the royalties',
    trigger: 'After Mathilde dates Anaïs’s score',
    operator: 'Acknowledge that Henri Valois registered music he did not compose. Give Gabriel his named packet and ask him to open it and read the current dividend split aloud. The other four packets remain sealed in Rémy’s row.',
    actionIds: ['gabriel-open-statement'],
    dependsOn: ['open-the-account'],
    essential: true,
  },
  {
    id: 'play-the-recording',
    phase: 'opening',
    title: 'Play Anaïs’s recording',
    trigger: 'After Gabriel exposes the hidden publisher',
    operator: 'Ask Colette to play the prepared test recording. While the room listens, quietly cue Solange to place the host-identifiable safe prop envelope addressed to Armand on the notebook.',
    actionIds: ['colette-play-recording', 'solange-place-envelope'],
    dependsOn: ['reveal-the-royalties'],
    essential: true,
  },
  {
    id: 'stage-collapse',
    phase: 'opening',
    title: 'Open the sixth envelope',
    trigger: 'During the second verse of the recording',
    operator: 'Notice the extra envelope, mime the fictional thumb prick, and perform the rehearsed seated collapse without contact. Remain still while Colette stops the recording and gives Mathilde the handkerchief cue.',
    actionIds: [],
    dependsOn: ['play-the-recording'],
    essential: true,
  },
  {
    id: 'recover-score',
    phase: 'opening',
    title: 'Recover Anaïs’s score',
    trigger: 'Immediately after Armand’s collapse',
    operator: 'Mathilde follows Colette’s prearranged handkerchief cue to the staged study, takes the separate replica original score from the west drawer, and returns holding it. For seated play, Rémy performs that movement only on Mathilde’s open instruction. The host remains still.',
    actionIds: ['mathilde-retrieve-score'],
    dependsOn: ['stage-collapse'],
    essential: true,
  },
  {
    id: 'declare-scene',
    phase: 'opening',
    title: 'Account for the papers',
    trigger: 'When Mathilde returns holding Anaïs’s score',
    operator: 'Rémy follows his authored cue, reads the evidence card from the safe envelope, and states the visible scene. Only after he finishes does the host sit up, become Game Master, invite the four holders of still-sealed packets to open them, and begin free investigation.',
    actionIds: ['remy-declare-scene'],
    dependsOn: ['recover-score'],
    essential: true,
  },
]
