import type { Character, PublicEvidence, RunBeat, TimelineBeat } from './types.js'

export const timeline: TimelineBeat[] = [
  {
    beat: 1,
    title: 'The innocent man',
    truth: 'Sixteen years ago, Jacques Vallon stole the Saint-Auban sapphire during a one-minute failure of the lights. Luc Bellande was convicted in his place and died in prison.',
    evidence: ['amelie-rumour', 'madame-ledger'],
  },
  {
    beat: 2,
    title: 'The blue account',
    truth: 'Armand Valère witnessed enough to know Luc was innocent. He recorded the theft, the false testimony, and every subsequent payment in Le Carnet Bleu, then used the truth to control everyone involved.',
    evidence: ['pierre-pocket', 'madame-glimpse'],
  },
  {
    beat: 3,
    title: 'The borrowed blade',
    truth: 'During the first course, Jacques borrowed Hélène’s silver paper knife to cut a ribbon. He appeared to return it, but left only its ornamental sheath beside her place.',
    evidence: ['francois-switch', 'amelie-jackets'],
  },
  {
    beat: 4,
    title: 'Page forty-seven',
    truth: 'Page forty-seven of the notebook named Jacques as the thief. Jacques saw it before dinner; after the murder, the numbered pages jumped directly from forty-six to forty-eight.',
    evidence: ['jacques-find', 'pierre-label'],
  },
  {
    beat: 5,
    title: 'The open terrace',
    truth: 'Pierre opened the terrace doors for Armand’s reconstruction of the old crime. The short garden passage then offered an unseen route between the dining room and study.',
    evidence: ['pierre-door', 'amelie-draught'],
  },
  {
    beat: 6,
    title: 'One minute of darkness',
    truth: 'Armand deliberately recreated the old lighting failure. Amélie started the gramophone and gave the agreed signal; the host extinguished the lights for exactly sixty seconds.',
    evidence: ['amelie-blackout', 'francois-clock'],
  },
  {
    beat: 7,
    title: 'The words in the study',
    truth: 'Jacques entered through the terrace and demanded page forty-seven. Armand refused, saying that a written confession had already gone to the examining magistrate.',
    evidence: ['jacques-confronts', 'amelie-laugh'],
  },
  {
    beat: 8,
    title: 'A deliberate murder',
    truth: 'Jacques killed Armand with Hélène’s silver paper knife and left it at the scene. The weapon was chosen in advance to place suspicion on her.',
    evidence: ['jacques-shove', 'scene-wound'],
  },
  {
    beat: 9,
    title: 'The missing leaf',
    truth: 'Jacques tore page forty-seven from Le Carnet Bleu and returned by the garden passage before the lights came back. He could destroy a page, but not the confession Armand had already sent.',
    evidence: ['jacques-flight', 'pierre-shadow'],
  },
  {
    beat: 10,
    title: 'The woman beside the body',
    truth: 'Hélène entered the study after Jacques left, not to kill Armand but to recover Luc Bellande’s love letters. Pierre found her over the body with the desk drawer open.',
    evidence: ['madame-search', 'pierre-sees'],
  },
]

export const publicEvidence: PublicEvidence[] = [
  {
    id: 'scene-wound',
    beat: 8,
    text: 'Armand’s staged wound is consistent with the blunt silver prop paper knife beside him. Its handle is engraved “H.V.”, but only the empty ornamental sheath had been visible at Hélène’s place.',
  },
]

export const cast: Character[] = [
  {
    id: 'jacques',
    name: 'Jacques Vallon',
    title: 'Financier and former secretary to the Marquis de Veyrac',
    costume: 'Immaculate black tie, pale gloves, a silver carnation',
    publicFace: 'Courteous, prosperous, and never surprised. You speak of the past as though it were a regrettable servant who has already been dismissed.',
    privateSecret: 'You stole the Saint-Auban sapphire and allowed Luc Bellande to die for it. Armand has blackmailed you ever since. Tonight you intend to kill him, remove page forty-seven from Le Carnet Bleu, and leave Hélène’s paper knife at the scene.',
    memories: [
      {
        id: 'jacques-find',
        kind: 'evidence',
        beat: 4,
        availableAfter: 'jacket-switch',
        text: 'When Armand displayed Le Carnet Bleu, you saw your name at the top of page forty-seven. The next page began with an account of payments from the Veyrac household.',
      },
      {
        id: 'jacques-confronts',
        kind: 'evidence',
        beat: 7,
        availableAfter: 'stage-murder',
        text: 'In the darkened study, Armand refused to surrender page forty-seven. He told you a complete confession was already on its way to the examining magistrate.',
      },
      {
        id: 'jacques-shove',
        kind: 'secret',
        beat: 8,
        availableAfter: 'stage-murder',
        text: 'You deliberately killed Armand with Hélène’s silver paper knife. This was not a quarrel that went too far; you came prepared to murder him.',
      },
      {
        id: 'jacques-flight',
        kind: 'secret',
        beat: 9,
        availableAfter: 'stage-murder',
        text: 'You tore page forty-seven from the notebook, left the paper knife beside Armand, and returned through the terrace before the lights came back.',
      },
      {
        id: 'jacques-duel',
        kind: 'colour',
        text: 'For fifteen years, Armand’s demands arrived in violet-black ink, each signed with a small blue cross. You have paid every one of them.',
      },
    ],
    actions: [
      {
        id: 'jacques-toast',
        text: 'Raise your glass to “Luc Bellande, whose empty chair has waited sixteen years.” Challenge Armand to say why you have all been summoned. While opening the host’s ribboned cigar box, borrow Hélène’s blunt silver prop paper knife and appear to return it by placing only its sheath beside her.',
        cue: 'After the first wine is poured and Hélène’s prop paper knife is in place',
        consequence: 'Forces the old case into the open and places the staged murder weapon in your possession.',
        essential: true,
        beat: 3,
        phase: 'dinner',
        physical: true,
        requires: ['paper-knife'],
      },
      {
        id: 'jacques-murder',
        text: 'During the blackout, take the safe terrace route to the study. Demand page forty-seven, perform the rehearsed confrontation, mime one thrust without touching the host, place the blunt prop beside them, tear out the replica page, and leave by the same route.',
        cue: 'When the lights go out and the host quietly calls you to the study',
        consequence: 'Creates the deliberate murder, the attempt to frame Hélène, and the missing page.',
        essential: true,
        beat: 8,
        phase: 'blackout',
        physical: true,
        requires: ['paper-knife', 'safe-route', 'controlled-lights', 'staged-area', 'no-contact'],
      },
    ],
  },
  {
    id: 'madame',
    name: 'Hélène de Veyrac',
    title: 'Widow of the late Marquis de Veyrac',
    costume: 'Black silk, a single strand of pearls, violet perfume',
    publicFace: 'A woman trained never to hurry, explain, or forgive. The house once belonged to your family, and you still behave as though everyone in it does too.',
    privateSecret: 'Luc Bellande was your lover, and your daughter was his child. You let him be convicted rather than expose her parentage. Armand kept Luc’s letters and used them to extort your late husband. Tonight you mean to recover them before the notebook is opened.',
    memories: [
      {
        id: 'madame-ledger',
        kind: 'evidence',
        beat: 1,
        text: 'Your late husband’s household ledger records a large payment to Armand three days after Luc Bellande withdrew his accusation against Jacques. The entry is marked only “for silence”.',
      },
      {
        id: 'madame-glimpse',
        kind: 'evidence',
        beat: 2,
        text: 'Before dinner, you saw Le Carnet Bleu open on Armand’s desk. One heading read “The Bellande affair”; beneath it were your initials and Jacques Vallon’s name.',
      },
      {
        id: 'madame-search',
        kind: 'secret',
        beat: 10,
        availableAfter: 'stage-false-culprit',
        text: 'You entered the study after the fatal confrontation and opened the west drawer to recover Luc’s letters. You did not help Armand or call for anyone.',
      },
      {
        id: 'madame-argument',
        kind: 'secret',
        text: 'This afternoon you told Armand that if he spoke your daughter’s name at dinner, you would see him buried before morning.',
      },
      {
        id: 'madame-perfume',
        kind: 'colour',
        text: 'Your violet perfume lingers in every room you enter. You know it will place you in the study whether or not you tell the truth.',
      },
    ],
    actions: [
      {
        id: 'madame-message',
        text: 'Pass Pierre a sealed note reading: “The west drawer. If I am delayed, open it before the police arrive.” Refuse to explain.',
        cue: 'Before Armand displays Le Carnet Bleu',
        consequence: 'Creates a genuine secret alliance and an apparently murderous piece of evidence.',
        essential: false,
        phase: 'dinner',
        physical: true,
        requires: ['paper-notes'],
      },
      {
        id: 'madame-search-action',
        text: 'After Jacques has left the study, enter and remove the tied bundle of replica letters from the west drawer. Remain beside Armand when Pierre arrives; do not invent an explanation until questioned.',
        cue: 'During the blackout, when the host quietly calls your name',
        consequence: 'Places you at the scene with a secret worth concealing, making you the strongest false suspect.',
        essential: true,
        beat: 10,
        phase: 'blackout',
        physical: true,
        requires: ['replica-letters', 'controlled-lights', 'staged-area', 'no-contact'],
      },
    ],
  },
  {
    id: 'francois',
    name: 'François Bellande',
    title: 'Pastry chef and son of the man condemned for the Saint-Auban theft',
    costume: 'A dark dinner suit with an old prison letter in the breast pocket',
    publicFace: 'Quiet and self-possessed. You have spent your life hearing that bitterness is unbecoming in the son of a criminal.',
    privateSecret: 'You forged the telegram claiming an examining magistrate will collect Le Carnet Bleu at dawn. You wanted to frighten Armand into producing the proof that would clear your father, but the forgery gives you an obvious reason to silence him.',
    memories: [
      {
        id: 'francois-switch',
        kind: 'evidence',
        beat: 3,
        availableAfter: 'jacket-switch',
        text: 'You watched Jacques borrow Hélène’s silver paper knife. When he moved away, you saw its decorated sheath beside her plate—but the silver handle itself was not inside it.',
      },
      {
        id: 'francois-clock',
        kind: 'evidence',
        beat: 6,
        availableAfter: 'stage-false-culprit',
        text: 'You timed the blackout against the gramophone record. It lasted exactly sixty seconds, and the fatal noise came before the final refrain.',
      },
      {
        id: 'francois-letter',
        kind: 'secret',
        text: 'The telegram from the examining magistrate is your forgery. No official is expected at dawn.',
      },
      {
        id: 'francois-kiss',
        kind: 'colour',
        text: 'Hélène visited your father once in prison. He refused to see her, but kept her unopened letter until he died.',
      },
      {
        id: 'francois-recipe',
        kind: 'colour',
        text: 'Armand has eaten at your pâtisserie every Thursday for eleven years and has never once paid his bill.',
      },
    ],
    actions: [
      {
        id: 'francois-switch-action',
        text: 'Place your father’s last prison letter beside Le Carnet Bleu and demand that Armand read both aloud. State that an examining magistrate is coming at dawn to collect the notebook.',
        cue: 'When Armand asks whether anyone still believes Luc Bellande was innocent',
        consequence: 'Makes the old conviction the moral centre of the dinner and forces Armand to display the notebook.',
        essential: true,
        beat: 2,
        phase: 'dinner',
        physical: true,
        requires: ['notebook', 'replica-letters'],
      },
    ],
  },
  {
    id: 'pierre',
    name: 'Pierre Mercier',
    title: 'Retired examining inspector',
    costume: 'A sober blue suit, old police watch, carefully polished shoes',
    publicFace: 'Methodical and dry. You correct imprecise times, unlocked doors, and other people’s recollections without being invited.',
    privateSecret: 'You led the investigation that convicted Luc Bellande. When Amélie contradicted Jacques’s alibi, the Marquis promised you promotion in exchange for losing her statement. You destroyed it.',
    memories: [
      {
        id: 'pierre-pocket',
        kind: 'evidence',
        beat: 2,
        text: 'Before dinner, Armand showed you the notebook. Page forty-seven began “J. Vallon left the blue salon during the failure of the lights.”',
      },
      {
        id: 'pierre-label',
        kind: 'evidence',
        beat: 4,
        text: 'After the murder, the notebook lies open at a rough edge. The numbering passes directly from page forty-six to page forty-eight.',
      },
      {
        id: 'pierre-door',
        kind: 'evidence',
        beat: 5,
        availableAfter: 'terrace-route',
        text: 'You opened both terrace doors for Armand’s reconstruction and personally checked that the garden passage to the study was clear.',
      },
      {
        id: 'pierre-shadow',
        kind: 'evidence',
        beat: 9,
        availableAfter: 'stage-murder',
        text: 'Seconds before the lights returned, you saw a pale-gloved man come in from the terrace. Jacques is the only guest wearing pale gloves.',
      },
      {
        id: 'pierre-sees',
        kind: 'evidence',
        beat: 10,
        availableAfter: 'stage-false-culprit',
        text: 'When you reached the study, Hélène stood over Armand holding a bundle of Luc Bellande’s letters. The west drawer was open, but the notebook was on the desk.',
      },
      {
        id: 'pierre-key',
        kind: 'secret',
        text: 'You destroyed Amélie’s original statement and wrote “witness confused” in its place. That false report secured Luc Bellande’s conviction and your promotion.',
      },
    ],
    actions: [
      {
        id: 'pierre-door-action',
        text: 'Open both terrace doors and leave them open. Announce that the garden passage now matches the conditions recorded on the night of the theft.',
        cue: 'When Armand says, “Let us give the past the same doors it had before”',
        consequence: 'Completes the reconstruction while unknowingly creating the murderer’s unseen route.',
        essential: true,
        beat: 5,
        phase: 'dinner',
        physical: true,
        requires: ['safe-route'],
      },
      {
        id: 'pierre-discovery',
        text: 'When the lights return, go directly to the study. Announce only what you see: Armand on the floor, Hélène beside him, the west drawer open, and Le Carnet Bleu missing a page.',
        cue: 'When the host restores the lights',
        consequence: 'Introduces the body, the damaged notebook, and the apparent culprit without interpreting them.',
        essential: true,
        beat: 10,
        phase: 'blackout',
        physical: true,
        requires: ['controlled-lights', 'staged-area', 'no-contact'],
      },
    ],
  },
  {
    id: 'amelie',
    name: 'Amélie Renaud',
    title: 'Former cabaret singer and the forgotten witness',
    costume: 'Midnight-blue dress, opera gloves, a small blue handkerchief',
    publicFace: 'Observant, amused, and apparently fearless. You remember voices better than faces and lies better than either.',
    privateSecret: 'You saw Jacques leave the blue salon during the original blackout, but you loved him and first gave him a false alibi. When you tried to correct it, Pierre destroyed your statement. Luc Bellande went to prison because both versions of your testimony failed him.',
    memories: [
      {
        id: 'amelie-rumour',
        kind: 'evidence',
        beat: 1,
        text: 'During the old lighting failure, you heard Jacques’s distinctive silver-topped cane strike the blue salon tiles. He was not beside you, despite the alibi you first gave him.',
      },
      {
        id: 'amelie-jackets',
        kind: 'evidence',
        beat: 3,
        availableAfter: 'jacket-switch',
        text: 'You saw Jacques close his left hand around Hélène’s silver paper knife. A moment later he placed only its blue velvet sheath beside her glass.',
      },
      {
        id: 'amelie-draught',
        kind: 'evidence',
        beat: 5,
        availableAfter: 'terrace-route',
        text: 'Once Pierre opened the terrace doors, a cold draught crossed the dining room from the garden passage. Anyone could reach the study without using the hall.',
      },
      {
        id: 'amelie-blackout',
        kind: 'evidence',
        beat: 6,
        availableAfter: 'blackout-signal',
        text: 'You started the gramophone and raised your blue handkerchief at the final refrain. The host cut the lights immediately, exactly as arranged.',
      },
      {
        id: 'amelie-laugh',
        kind: 'evidence',
        beat: 7,
        availableAfter: 'stage-murder',
        text: 'From the dining room you heard Jacques say, “Give me page forty-seven.” Armand replied, “A page can burn; my confession cannot.” Then came a single sharp cry.',
      },
      {
        id: 'amelie-key',
        kind: 'secret',
        text: 'Your first statement gave Jacques a false alibi. Your second told the truth, but Pierre destroyed it. You have concealed both facts for sixteen years.',
      },
    ],
    actions: [
      {
        id: 'amelie-blackout-action',
        text: 'Place the gramophone track at its marked position. At the final refrain, raise your blue handkerchief. The host—not you—controls the real lights.',
        cue: 'After the terrace doors are open and Armand announces the reconstruction',
        consequence: 'Begins the exact one-minute recreation of the old crime under safe host control.',
        essential: true,
        beat: 6,
        phase: 'dinner',
        physical: false,
        requires: ['controlled-lights'],
      },
    ],
  },
]

export const runPlan: RunBeat[] = [
  {
    id: 'coded-toast',
    phase: 'dinner',
    title: 'Name the absent guest',
    trigger: 'After the first wine is poured',
    operator: 'Give Jacques the ribboned cigar box and let his toast force the Bellande case into the open. Use only the prepared blunt prop paper knife.',
    actionIds: ['jacques-toast'],
    dependsOn: [],
    essential: true,
  },
  {
    id: 'false-message',
    phase: 'dinner',
    title: 'Pass the west-drawer note',
    trigger: 'Before the notebook is displayed',
    operator: 'Give Hélène a quiet moment to pass her sealed note to Pierre.',
    actionIds: ['madame-message'],
    dependsOn: [],
    essential: false,
  },
  {
    id: 'jacket-switch',
    phase: 'dinner',
    title: 'Open the Bellande case',
    trigger: 'When Armand asks whether anyone still believes Luc was innocent',
    operator: 'Let François produce the prison letter and forged telegram. Place Le Carnet Bleu where everyone can see it, open at the replica of page forty-seven.',
    actionIds: ['francois-switch-action'],
    dependsOn: [],
    essential: true,
  },
  {
    id: 'terrace-route',
    phase: 'dinner',
    title: 'Recreate the old room',
    trigger: 'After the notebook and prison letter are on the table',
    operator: 'Announce the reconstruction and say, “Let us give the past the same doors it had before,” cueing Pierre to open the terrace.',
    actionIds: ['pierre-door-action'],
    dependsOn: ['jacket-switch'],
    essential: true,
  },
  {
    id: 'blackout-signal',
    phase: 'dinner',
    title: 'Recreate the lost minute',
    trigger: 'After the terrace is open and Jacques has named Luc Bellande',
    operator: 'Announce that the original theft occurred during one minute of darkness. Wait for Amélie’s handkerchief signal; do not cut the lights before both prerequisite beats are complete.',
    actionIds: ['amelie-blackout-action'],
    dependsOn: ['coded-toast', 'terrace-route'],
    essential: true,
  },
  {
    id: 'stage-murder',
    phase: 'blackout',
    title: 'Stage the murder in the study',
    trigger: 'Immediately after Amélie’s signal',
    operator: 'Cut the lights. Quietly call Jacques by the safe route, perform the confrontation, stage the no-contact murder, leave the blunt prop at the scene, and let Jacques remove the replica page and depart.',
    actionIds: ['jacques-murder'],
    dependsOn: ['blackout-signal'],
    essential: true,
  },
  {
    id: 'stage-false-culprit',
    phase: 'blackout',
    title: 'Place Hélène beside the body',
    trigger: 'After Jacques has left the study',
    operator: 'Call Hélène into the study to retrieve the replica letters. Restore the lights only when she is in place, then cue Pierre to report exactly what he sees.',
    actionIds: ['madame-search-action', 'pierre-discovery'],
    dependsOn: ['stage-murder'],
    essential: true,
  },
]
