/** Hard production limits for authored narrative load. */
export const storyQualityBudgets = Object.freeze({
  playerPacketWords: 450,
  factsPerPlayer: 6,
  relationshipsPerPlayer: 4,
  traitsPerPlayer: 3,
  objectivesPerPlayer: 3,
  totalStartingFacts: 35,
  totalRelationships: 20,
  openingSteps: { minimum: 4, maximum: 6 },
  openingWords: 400,
  openingInstructions: 20,
  openingCuesPerPlayer: 2,
  setupRequirements: 8,
  textWords: Object.freeze({
    premise: 140,
    solutionSummary: 220,
    publicFace: 50,
    invitationPretext: 40,
    invitationPromise: 40,
    privateIdentity: 60,
    privateObjective: 45,
    privateSecret: 60,
    trait: 12,
    objectiveTitle: 10,
    objectiveText: 30,
    relationship: 30,
    fact: 45,
    publicEvidence: 60,
    solutionTruth: 60,
    openingTrigger: 24,
    openingInstruction: 45,
    clue: 45,
    setupRequirement: 45,
    actGoal: 60,
    stageDescription: 50,
  }),
})
